### PR TITLE
Add patch to use native file chooser

### PR DESCRIPTION
**Pull request by cagatay-y**
This allows attaching media to toots from the sandbox and solves #1.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
This should be implemented upstream.

**Comment by cagatay-y** [comment]
I created a pull request but it has been 25 days since upstream last got a commit. Adding permissions may be an option.

**Comment by cagatay-y** [comment]
Just realized the patch breaks the file filter functionality. Seems like permissions are needed.

**Comment by TingPing** [comment]
The portal supports filters so something is wrong there.

**Pull request closed without merging**
