### PR TITLE
Update flatpak runtime

### LINKED ISSUE #18: Update org.gnome.Platform - EoL
org.gnome.Platform branch 40 is now End-of-Life and needs to be updated :)

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Fixes #18

### CODE REVIEW

**Comment by hfiguiere** [comment]
I believe libhandy is in the runtime now and can be removed from the manifest.

**Comment by WhyNotHugo** [comment]
I'll let the build-bot build it without libhandy and see if it works.

**Comment by hfiguiere** [comment]
LOL the build failure is on libhandy...
(it's the first triggered build)

**Comment by hfiguiere** [comment]
build failure is now same as on #19.

**Comment by harmathy** [comment]
You need at least the patches from bleakgrey/tootle/pull/322, bleakgrey/tootle/pull/339 and bleakgrey/tootle/pull/346. See my [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/?h=tootle) for reference.

**Comment by WhyNotHugo** [comment]
Hmmm.. according to the docs [a `url` for a patch is not allowed, it needs to be a path to a file in the source directory](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#idm46203909168976)... but then we need a tarball with both the sources AND the patch? That doesn't make sense.

**Comment by hfiguiere** [comment]
Patches are added to the flatpak repo.

**Comment by WhyNotHugo** [comment]
What do you mean?

**Comment by hfiguiere** [comment]
```
$wget https://patch-diff.githubusercontent.com/raw/bleakgrey/tootle/pull/322.patch
$git add 322.patch
```

(you can rename the patch whatever you want)

and then in the manifest `path` is where to find the patch relative to the manifest.

**Comment by harmathy** [comment]
The patches from https://github.com/bleakgrey/tootle/pull/339 and https://github.com/bleakgrey/tootle/pull/346 might not be applicable to the stable 1.0 version. I ported all patches to the stable release https://github.com/harmathy/tootle/tree/maintanence

**Comment by harmathy** [comment]
But you can just grab the patch files from my [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/?h=tootle) repository.

**Comment by cagatay-y** [comment]
The runtime has been updated to GNOME 42 with #22, together with the relevant patches in this PR.

**Pull request closed without merging**
